travis:
  secure:
    BINSTAR_TOKEN: q14oMVs/A839Dfn5ouAxCSjIftr/hWvBLiFh40M6MxXp7eycl2AO0SWtz7721B2DmwP0+ED7nv5ZJ+/9CIJl9IxqQ8o5ocaLbx52hbggA4KveFaJ+XJkDWSVqUh9L+W/BhrMrjL7mltGij5SEa9Kw4Biop3uiAcPWuwM2mDkCKotsKtUGiPJ0iO7WW8+POkKNmIlGy/s4kEhzOcglabD2guLsijYv0CCrIWj2IRAKOojP3iyj6g5i+PNRfaGywX2v6b8VNF8YIdEsBzDgqeeduUrgMMvgkvEA/9iMkWHpweyYmWJiYbD4JxPmeo1wOv7D2twV1xLxdCUH0LjMwoTTWhepl0oizoJomkejgGBRRMZRuYplDp6lWbwkUofiZ5is5OHfbXam6sKypto+IpwNisYL3lIpGPPxnbfI6wCaOix51OkeS3olgbRYjcVYz45vl+mb63PRogQRHJo5GRwGGrVgCVrkyqhIBonVtGaUXxaLXzrrS2oWBqdI+m5UAflbZE97Cd2rkjSYvi2+wFxHs+a+QTevzZ6hdPkgSLPPcGbEAfPaegbGUumbzbZhWkdCuuEeyDRV6Osoc4Z88Hhm3ZxBeRYfYT5AFgxxqK4mBzdLbWTTpobRa0fwcM/fa2f7yVll0v16Dq924mdrVhrPhcW0tOX2F/bO8fe9vLfYbA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
