travis:
  secure:
    BINSTAR_TOKEN: zVGcVwCpBWRtD8H+pb49VmmcBwIy39otEcg3c7Qp+XcZIpHDkTu37jm5NkzvoY0Scm6FEN/vRNBeliqv6sgU/WInvaX+T1Ro5ssFVVKiGBJnKJMtCVSuELCnGOf2kV0Kmkm/ldYj8U9wAozMdiwXxB6h1otjJReq6Lo6KTS7HyEnHPEO9sdclcokOlCFPhkDlJUw0Ggt4tj1X77wio+yck9JzocAqKSBzB20mVMKT6/dbueVabF/exxVfE525uPxrHXMBD+syh2QAz2Dte7ce5yOsJBNbkMkyqDeqO9smDMrn7vkANt26go1R4wRtJ1UIQk66BjeIrjeMlop0jTsQFmjcnhul6IPtvvJZRTUJOOsh/r02MKZdntcw4HwmHAE1ehsPK6pLkyf6n6zcJpsEwzgs4HRTcFtHoapAh0XdacGyIqsUbOc1jsFhF/3wCMYwFayYf0XwrM++hRsXVQUN3TGuYlsmzSL4zn6st9RVXrJXMjLSIxL/TMjOUg4bL73DW6dTbqukWFQg7oD/AFOGRpNc3hFfva+bOCAP+exf70FVJYu1ffgTnL/+2+7hBb0H1x9S5KHP17kdHPl8uE9roF8D/CLkQfgTzDlXU6b3uvNbC8oYBQqflDz4hCC5NOPjvPpUphaGMAy2cEnKu55QTCjGMGAmkSMr5gNV35pjis=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
